sudo: false
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
    apt:
        packages:
            - libgmp-dev

env:
    - ARGS="stack"
    - ARGS="stack --resolver lts-3 --stack-yaml stack-lts3.yaml"
    - ARGS="stack --resolver lts-4"
    - ARGS="stack --resolver lts-5"
    - ARGS="stack --resolver lts-6"
    - ARGS="stack --resolver lts"
    - ARGS="stack --resolver nightly"

matrix:
    fast_finish: true
    allow_failures:
        - env: ARGS="stack --resolver nightly"


before_install:
    - ./ci/before_install $ARGS

script:
    - ./ci/script $ARGS

cache:
    directories:
        - $HOME/.stack
