#!/usr/bin/env bash

set -euo pipefail

ARGS="$*"

case "${ARGS[0]}" in

    "stack")

        ARGS="${ARGS:1}"

        # Download and unpack the stack executable
        mkdir -p "~/.local/bin"
        export PATH="$HOME/.local/bin:$PATH"
        curl -L https://www.stackage.org/stack/linux-x86_64 \
            | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

        stack --version
        stack $ARGS --no-terminal setup
        stack $ARGS --no-terminal install hlint hscolour cabal-install

        ;;

    "cabal")

        echo "Cabal build dummy working"

        ;;

    *)

        echo "Invalid invocation: $ARGS"
        exit 1

esac
