#!/usr/bin/env bash

set -evxuo pipefail

ARGS="$@"

case "${ARGS[0]}" in

    "stack")

        ARGS="${ARGS[@]:1}"

        stack $ARGS --no-terminal test --coverage --ghc-options -Werror
        stack $ARGS --no-terminal test --flag stgi:doctest --ghc-options -Werror
        stack $ARGS --no-terminal haddock --no-haddock-deps

        stack $ARGS --no-terminal sdist
        cabal check
        hlint src test app

        ;;

    "cabal")

        echo "Cabal build dummy working"

        ;;

    *)

        echo "Invalid invocation: $ARGS"
        exit 1

esac
